const express = require('express');
const router = express.Router();
const mainController = require('../controller/mainController');
const authMiddleware = require('../middleware/authMiddleware');

router.get('/',authMiddleware, mainController.index);
// router.get('/cart',authMiddleware, mainController.cart); 

router.get('/accordion',authMiddleware, mainController.accordion);
router.get('/activity',authMiddleware, mainController.activity);
router.get('/add_student',authMiddleware, mainController.add_student);
router.get('/add_teacher',authMiddleware, mainController.add_teacher);
router.get('/alert',authMiddleware, mainController.alert);
router.get('/app_calender',authMiddleware, mainController.app_calender);
// router.get('/app_profile',authMiddleware, mainController.app_profile);
router.get('/badge', authMiddleware,mainController.badge);
router.get('/button_group',authMiddleware, mainController.button_group);
router.get('/button',authMiddleware, mainController.button);
router.get('/calendar',authMiddleware, mainController.calendar);
router.get('/card',authMiddleware, mainController.card);
router.get('/carousel',authMiddleware, mainController.carousel);
router.get('/chartist',authMiddleware, mainController.chartist);
router.get('/chartjs',authMiddleware, mainController.chartjs);
router.get('/chat',authMiddleware, mainController.chat);
router.get('/dropdown', authMiddleware,mainController.dropdown);authMiddleware,
// router.get('/ecom_checkout',authMiddleware, mainController.ecom_checkout);
router.get('/ecom_customers',authMiddleware, mainController.ecom_customers);
router.get('/ecom_invoice',authMiddleware, mainController.ecom_invoice);
// router.get('/ecom_product_details',authMiddleware, mainController.ecom_product_details);
// router.get('/ecom_product_grid',authMiddleware, mainController.ecom_product_grid);
router.get('/ecom_product_list',authMiddleware, mainController.ecom_product_list);
router.get('/ecom_product_order',authMiddleware, mainController.ecom_product_order);
// router.get('/edit_profile',authMiddleware, mainController.edit_profile);
router.get('/email_compose',authMiddleware, mainController.email_compose);
router.get('/email_inbox',authMiddleware, mainController.email_inbox);
router.get('/email_read',authMiddleware, mainController.email_read);
router.get('/file_manager',authMiddleware, mainController.file_manager);
router.get('/finance',authMiddleware, mainController.finance);
router.get('/flot',authMiddleware, mainController.flot);
router.get('/food_details',authMiddleware, mainController.food_details);
router.get('/food',authMiddleware, mainController.food);
router.get('/form_ckeditor',authMiddleware, mainController.form_ckeditor);
router.get('/form_elements',authMiddleware, mainController.form_elements);
router.get('/form_pickers',authMiddleware, mainController.form_pickers);
router.get('/form_validation_jquery',authMiddleware, mainController.form_validations_jquery);
router.get('/form_wizard',authMiddleware, mainController.form_wizard);
router.get('/grid',authMiddleware, mainController.grid);
router.get('/index_2',authMiddleware, mainController.index_2);
router.get('/index',authMiddleware, mainController.index);
router.get('/lightgallery',authMiddleware, mainController.lightgallery);
router.get('/list_group',authMiddleware, mainController.list_group);
router.get('/map_jqvmap',authMiddleware, mainController.map_jqvmap);
router.get('/modal',authMiddleware, mainController.modal);
router.get('/morris',authMiddleware, mainController.morris);
router.get('/nestable', authMiddleware,mainController.nestable);
router.get('/noui_slider',authMiddleware, mainController.noui_slider);
router.get('/page_empty',authMiddleware, mainController.page_empty);
router.get('/page_error_400',authMiddleware, mainController.page_error_400);
router.get('/page_error_403',authMiddleware, mainController.page_error_403);
router.get('/page_error_404',authMiddleware, mainController.page_error_404);
router.get('/page_error_500',authMiddleware, mainController.page_error_500);
router.get('/page_error_503',authMiddleware, mainController.page_error_503);
router.get('/page_lock_screen',authMiddleware, mainController.page_lock_screen);
router.get('/page_login', mainController.page_login);
router.get('/page_register', mainController.page_register);
router.get('/pagination',authMiddleware, mainController.pagination);
router.get('/peity', mainController.peity);
router.get('/popover',authMiddleware, mainController.popover);
router.get('/post_details',authMiddleware, mainController.post_details);
router.get('/progressbar',authMiddleware, mainController.progressbar);
router.get('/select2',authMiddleware, mainController.select2);
router.get('/sparkline', authMiddleware,mainController.sparkline);
router.get('/student_details',authMiddleware, mainController.student_details);
// router.get('/student', mainController.student);authMiddleware,
router.get('/sweetalert', authMiddleware,mainController.sweet_alert);
router.get('/tab',authMiddleware, mainController.tab);
router.get('/table_bootstrap', authMiddleware,mainController.table_bootstrap);
router.get('/table_datatable',authMiddleware, mainController.table_datatable);
router.get('/teacher_details',authMiddleware, mainController.teacher_details);
// router.get('/teacher', mainController.teacher);
router.get('/toastr',authMiddleware, mainController.toastr);
router.get('/typography',authMiddleware, mainController.typography);
router.get('/user',authMiddleware, mainController.user);
router.get('/widget_card', authMiddleware,mainController.widget_card);
router.get('/widget_chart',authMiddleware, mainController.widget_chart);
router.get('/widget_list',authMiddleware, mainController.widget_list);
module.exports = router;